### ISSUE TITLE
Opening a popup gets broken by prototype.js

### ISSUE THREAD

**Issue by marcin-synak** [zewish/rmodal.js#20]
I had a misfortune of integrating a popup engine which uses RModal.js with a webpage that uses Prototype.js v1.7 (part of some Magento installation).

Trying to open a popup, e.g. like this:

`var p = new RModal(...options here...);`
`p.open();`

results in an exception:

`TypeError: this.each is not a function prototype.js:883:5`
`findAll prototype.js:883:5`
`s.prototype.elements rmodal.min.js:1:2369`
`s.prototype.focus rmodal.min.js:1:2585`
`s.prototype._doOpen rmodal.min.js:1:1537`
`s.prototype.open rmodal.min.js:1:1227`

The popup itself is displayed, but the code breaks here, e.g. "afterOpen" callback is not executed.

I've tracked the problem down to this line in RModal.js, function RModal.prototype.elements:

`return [].filter.call(`

It seems that Prototype.js substitutes "filter" function with its own "findAll" function which does not work correctly in this context (it tries to iterate over "NodeList" object and fails).

Every RModal popup with "focus=true" option is affected.

I know this is not RModal issue but rather a problem with extremely invasive Prototype.js library.
But maybe there is some walkaround you could suggest?

Maybe the code could be patched up to avoid using "filter" method and be more prototype-friendly? I can modify the popup engine, but I cannot modify the website.

Disabling the focus should obviously work, but that's a feature and I'd like to keep it :)

**Comment by zewish** [comment]
I had a quick look at the prototype.js source code. The issue is they depend on the missing `each()` function, that's not available on the window.NodeList. So with some more prototype patching you would probably make the modal work as expected.

I'd use something like that.
```js
window.NodeList.prototype.each = window.NodeList.prototype.forEach;
```

I know it may not be the cleanest solution, but prototype.js itself messes with the prototype, so I guess this shouldn't be too big of an issue for your app.

**Comment by zewish** [comment]
Hey!

I had a quick look at the prototype.js source code. The issue is they depend on the missing `each()` function, that's not available on the window.NodeList. So with some more prototype patching you would probably make the modal work as expected.

I'd use something like that.

```js
window.NodeList.prototype.each = window.NodeList.prototype.forEach;
```

I know it may not be the cleanest solution, but prototype.js itself messes with the prototype, so I guess this shouldn't be too big of an issue for your app.

Hope that helps.

**Comment by marcin-synak** [comment]
Thanks! I can easily add this line of code to my app. To make it a little less invasive, I've included a check:

```javascript
// fix for websites using prototype.js
if (typeof window.NodeList.prototype.each === 'undefined') {
    window.NodeList.prototype.each = window.NodeList.prototype.forEach;
}
```

Just in case somebody else already implemented this in some way.

Some trivia - I've found this problem while testing popups that automatically close after a number of seconds. I was using `afterOpen` callback to setup a timeout and it did not work correctly.
